### ISSUE TITLE
上传code的zip包的时候一直提示tomeout(10000)

### ISSUE THREAD

**Issue by GitNiko** [aliyun/fun#12]
```js
RequestTimeoutError: PUT http://1634907079716801.cn-shanghai.fc.aliyuncs.com/2016-08-15/services/demo/functions/helloworld2 timeout(10000).
 PUT http://1634907079716801.cn-shanghai.fc.aliyuncs.com/2016-08-15/services/demo/functions/helloworld2 failed.
    at Timeout.setTimeout [as _onTimeout] (/Users/niko/workspace/prac-aliyun/func/node_modules/httpx/lib/index.js:110:17)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! func@1.0.0 deploy.test: `DEBUG=* fun deploy TEST`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the func@1.0.0 deploy.test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```
package.json
```js
{
  "name": "func",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "deploy.test": "DEBUG=* fun deploy TEST"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@alicloud/fun": "^1.4.0"
  },
  "dependencies": {
    "tablestore": "^4.0.10"
  }
}

```
如果不上传zip，把dependencies去掉，是可以deploy成功的。

哪里出了问题？

**Comment by JacksonTian** [comment]
请更新下 fun，时间加长到了 20s

**Comment by GitNiko** [comment]
更新后可以了

**Comment by JacksonTian** [comment]
感谢使用本工具。
