### ISSUE TITLE
Update from 2.10.1 to 2.10.2 breaks deployment

### ISSUE THREAD

**Issue by roura356a** [aliyun/fun#164]
I updated my working Fun project on `2.10.1` to `2.10.2` and, when doing `fun deploy`, I get the following error:
```
Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:508:9)
    at Object.exports.execFile (child_process.js:218:15)
    at exports.exec (child_process.js:148:18)
    at /usr/lib/node_modules/@alicloud/fun/node_modules/node-machine-id/dist/index.js:1:7525
    at new Promise (<anonymous>)
    at new n (/usr/lib/node_modules/@alicloud/fun/node_modules/node-machine-id/dist/index.js:1:3976)
    at s (/usr/lib/node_modules/@alicloud/fun/node_modules/node-machine-id/dist/index.js:1:7481)
    at getFcClient (/usr/lib/node_modules/@alicloud/fun/lib/deploy/deploy-support.js:39:21)
    at <anonymous>
```
--

My `template.yml` includes LogService, FC, TableStore and API.

**Comment by roura356a** [comment]
It was running out of memory. My fault!
