### ISSUE TITLE
fun help是提示命令吗？

### ISSUE THREAD

**Issue by heartshuai** [aliyun/fun#29]
请问如何做到上传到函数计算的同时自动安装打包依赖模块  我这里没有实现这个效果，如何将整个文件夹进行上传呢？

**Comment by JacksonTian** [comment]
fun 收集 package.json 里的依赖，在远端相同运行环境里进行依赖构建。然后下载合并本地代码，打包上传到函数计算。

**Comment by heartshuai** [comment]
请问如何在docker里面使用呢，
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@alicloud/fun/bin/fun.js:35:3)



请问fun help命令怎么使用呢
