### ISSUE TITLE
测试fun deploy但始终报错 TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by senseluo** [aliyun/fun#35]
hi all,

在参照[官方文档](https://help.aliyun.com/document_detail/64204.html)执行 `fun deploy` 时遇到以下错误

```shell
bogon:fun_test senseluo$ fun deploy
Function compute(cn-shanghai):
  service fc ok.
TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:99:16)
    at Object.md5 (/Users/senseluo/.nvm/versions/node/v8.10.0/lib/node_modules/@alicloud/fun/node_modules/kitx/lib/index.js:49:12)
    at buildDeps (/Users/senseluo/.nvm/versions/node/v8.10.0/lib/node_modules/@alicloud/fun/lib/deps.js:225:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

不知道是不是一个bug，我的代码在 https://github.com/senseluo/aliyun_fun_demo
（其中的faas中id/key/secret已替换成假的）

谢谢~

**Comment by JacksonTian** [comment]
这是一个bug，目前我已经修复了，你再试一下。

**Comment by senseluo** [comment]
嗯 测了是好了 感谢 @JacksonTian
