### ISSUE TITLE
example 运行报错

### ISSUE THREAD

**Issue by WangZishi** [aliyun/fun#7]
根据 README 配置上 credentials 和 role， fun deploy 报错

![image](https://user-images.githubusercontent.com/8288105/34710808-ad193938-f557-11e7-8a20-40c339d72b0c.png)

**Comment by JacksonTian** [comment]
请在 fun 之前设置下 DEBUG=* ，看看具体是什么问题

**Comment by WangZishi** [comment]
```
PS C:\Users\ynh2\Test\Aliyun-Test\fun-test> $env:DEBUG="*"
PS C:\Users\ynh2\Test\Aliyun-Test\fun-test> fun deploy
  fun:conf exitst config: {"accountid":"wangzishi@30148339","accessKeyId":"LTAIp5U8m9YlsC0Q","accessKeySecret":"***","role":{"name":"apigatewayAccessFC"},"function-compute":{"region":"cn-beijing","services":[{"name":"fc","description":"fc test","functions":[{"name":"helloworld","description":"Hello world!","handler":"helloworld.index","codes":["helloworld.js"]}]}]},"api-gateway":{"endpoint":"http://apigateway.cn-hangzhou.aliyuncs.com","groups":[{"name":"apigw_fc","description":"API Gateway & Function Compute","apis":[{"name":"helloworld","method":"GET","path":"/helloworld","function":"cn-beijing/fc/helloworld"}]}]}} +0ms
Function compute(cn-beijing):
  lambda stringToSign: GET


Tue, 23 Jan 2018 07:12:12 GMT
x-fc-account-id:wangzishi@30148339
/2016-08-15/services/fc +7ms
  lambda request headers: {"accept":"application/json","date":"Tue, 23 Jan 2018 07:12:12 GMT","host":"wangzishi@30148339.cn-beijing.fc.aliyuncs.com","user-agent":"Node.js(v8.9.4) OS(win32/x64) SDK(@alicloud/fc@v1.2.3)","x-fc-account-id":"wangzishi@30148339","authorization":"FC LTAIp5U8m9YlsC0Q:F5bw+zzLarqcWFYEkveINvx0RPwS1b+X7WMy1q8I8XI="} +0ms
  httpx > GET /2016-08-15/services/fc HTTP/1.1 +295ms
  httpx > accept: application/json +1ms
  httpx > date: Tue, 23 Jan 2018 07:12:12 GMT +0ms
  httpx > host: wangzishi@30148339.cn-beijing.fc.aliyuncs.com +0ms
  httpx > user-agent: Node.js(v8.9.4) OS(win32/x64) SDK(@alicloud/fc@v1.2.3) +1ms
  httpx > x-fc-account-id: wangzishi@30148339 +0ms
  httpx > authorization: FC LTAIp5U8m9YlsC0Q:F5bw+zzLarqcWFYEkveINvx0RPwS1b+X7WMy1q8I8XI= +0ms
  httpx > Connection: keep-alive +0ms
  httpx >  +0ms
  httpx >  +1ms
  httpx < HTTP/1.1 400 Bad Request: malformed Host header +0ms
  httpx < content-type: text/plain; charset=utf-8 +0ms
  httpx < connection: close +0ms
  lambda response status: 400 +0ms
  lambda response headers: {"content-type":"text/plain; charset=utf-8","connection":"close"} +1ms
  httpx  +1ms
  httpx 400 Bad Request: malformed Host header +1ms
  lambda response body: 400 Bad Request: malformed Host header +0ms
FCundefinedError: GET /services/fc failed with 400. requestid: undefined, message: undefined.
    at Client.request (C:\Users\ynh2\AppData\Local\nvs\node\8.9.4\x64\node_modules\@alicloud\fun\node_modules\@alicloud\fc\lib\client.js:177:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
PS C:\Users\ynh2\Test\Aliyun-Test\fun-test>
```

**Comment by JacksonTian** [comment]
accountid 写错了。

**Comment by JacksonTian** [comment]
在你的 https://account.console.aliyun.com/#/secure 的 账号ID  那串数字。

**Comment by WangZishi** [comment]
但是公司给的是子账号，那串数字不是主账号的id吗？我应该用主账号吗？

**Comment by JacksonTian** [comment]
用主账号的 accountid，可以用子账号的 AK。
